apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: whatsapp-web-autoscaler
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whatsapp-web-deployment
  targetCPUUtilizationPercentage: 60
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-web-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: web
  selector:
    name: whatsapp-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-web-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: whatsapp-web
    spec:
      restartPolicy: "Always"
      containers:
      - name: whatsapp-web
        image: docker.whatsapp.biz/web:v2.25.4
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory : 128Mi
          requests:
            cpu: "0.15"
            memory : 128Mi
        ports:
        - containerPort: 443
          protocol: TCP
          name: web
        env:
        - name: WA_DB_ENGINE
          value: MYSQL
        - name: WA_APP_MULTICONNECT
          value: '1'
        - name: WA_DB_HOSTNAME
          value: mysql-service
        - name: WA_DB_PORT
          value: 3306
        - name: WA_DB_USERNAME
          value: root
        - name: WA_DB_PASSWORD
          value: testpass
        - name: WA_WEB_SERVERNAME
          value: 'whatsapp-web-service'
        volumeMounts:
        - name: whatsapp-media
          mountPath: /usr/local/wamedia
      volumes:
      - name: whatsapp-media
        nfs:
          server: fs-6f79f3a4.efs.eu-west-1.amazonaws.com
          path: /phani-whatsapp-service
